const Note = require('./Notenew')
// Note.listIncome()
// Note.listExpense()
// Note.addIncome("gaji lembur", 3000000)
// Note.addExpense("Cicilan Rumah", 4000000)
Note.listIncome()
yuhu = Note.balance()
console.log(yuhu)